name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jvm_flag:
          - "-XX:+UseG1GC"
          - "-XX:MaxHeapSize=512m"
          - "-XX:+PrintGCDetails"
          - "-XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation"
          - "-XX:+UseParallelGC"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Log JVM Flag
      run: |
        echo "Running tests with JVM flag: ${{ matrix.jvm_flag }}"

    - name: Build and Test with Maven
      timeout-minutes: 15
      run: |
        MAVEN_OPTS="${{ matrix.jvm_flag }}" ./mvnw clean test -Djava.awt.headless=true

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Fail if coverage has not improved.
      run: |
        coverage=$COVERAGE
        threshold=24.46
        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
          echo "Coverage is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi
